# Import Libraries

In [1]:
# Import pandas for data analysis
import pandas as pd

# Import numpy for numerical calculations
import numpy as np

# Import os for checking files
import os

# Display all columns in output
pd.set_option("display.max_columns", None)

# Display maximum 100 rows
pd.set_option("display.max_rows", 100)

# Print confirmation message
print("All libraries imported successfully.")

All libraries imported successfully.

# Load CSV Files

In [2]:
# Load the retail orders CSV file
orders = pd.read_csv("retail-orders-raw.csv")

# Load the retail data dictionary CSV file
data_dictionary = pd.read_csv("retail-data-dictionary.csv")

# Print confirmation
print("Both CSV files loaded successfully.")

Both CSV files loaded successfully.

# Display Data

In [3]:
# Display first five rows of retail orders data
print("Retail Orders Data:")
display(orders.head())

# Display first five rows of data dictionary
print("Retail Data Dictionary:")
display(data_dictionary.head())

Retail Orders Data:

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03/01/2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-01-05,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid

Retail Data Dictionary:

,column,data_type,business_definition,quality_rule
0,order_id,string,Unique order identifier,Required and unique
1,order_date,date,Date the customer placed the order,Required ISO date between 2025-01-01 and today
2,customer_segment,category,Commercial customer segment,Student Fresher or Professional after normaliz...
3,city,string,Customer billing city,Required non-empty text
4,category,category,Product family,Learning Kit Course Access or Mentor Session

# Dataset Shape

In [4]:
# Display the number of rows and columns
print("Orders Dataset Shape:", orders.shape)

# Display data dictionary shape
print("Data Dictionary Shape:", data_dictionary.shape)

Orders Dataset Shape: (12, 9)
Data Dictionary Shape: (9, 4)

# Column Names

In [5]:
# Display all column names
print("Orders Dataset Columns:")
print(orders.columns.tolist())

print("\nData Dictionary Columns:")
print(data_dictionary.columns.tolist())

Orders Dataset Columns:
['order_id', 'order_date', 'customer_segment', 'city', 'category', 'quantity', 'unit_price', 'discount_pct', 'payment_status']

Data Dictionary Columns:
['column', 'data_type', 'business_definition', 'quality_rule']

# Dataset Information

In [6]:
# Display complete information about the orders dataset
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          12 non-null     str
 1   order_date        11 non-null     str
 2   customer_segment  12 non-null     str
 3   city              11 non-null     str
 4   category          12 non-null     str
 5   quantity          12 non-null     str
 6   unit_price        12 non-null     int64
 7   discount_pct      11 non-null     float64
 8   payment_status    12 non-null     str
dtypes: float64(1), int64(1), str(7)
memory usage: 996.0 bytes

# Missing Values

In [7]:
# Count missing values in each column
missing_values = orders.isnull().sum()

# Create missing value report
missing_report = pd.DataFrame({
    "Column": missing_values.index,
    "Missing Values": missing_values.values
})

# Display missing value report
display(missing_report)

             Column  Missing Values
0          order_id               0
1        order_date               1
2  customer_segment               0
3              city               1
4          category               0
5          quantity               0
6        unit_price               0
7      discount_pct               1
8    payment_status               0

# Duplicate Values

In [8]:
# Count duplicate rows
duplicate_count = orders.duplicated().sum()

# Print duplicate count
print("Total Duplicate Rows:", duplicate_count)

Total Duplicate Rows: 1

# Unique Values

In [9]:
# Count unique values in each column
unique_values = orders.nunique()

# Create unique values report
unique_report = pd.DataFrame({
    "Column": unique_values.index,
    "Unique Values": unique_values.values
})

# Display unique values report
display(unique_report)

             Column  Unique Values
0          order_id             11
1        order_date             10
2  customer_segment              4
3              city              7
4          category              3
5          quantity              5
6        unit_price              3
7      discount_pct              5
8    payment_status              5

# Numerical Columns

In [10]:
# Select numerical columns
numeric_columns = orders.select_dtypes(include=np.number).columns

# Display numerical column names
print("Numerical Columns:")
print(numeric_columns.tolist())

# Display statistical summary
display(orders[numeric_columns].describe())

Numerical Columns:
['unit_price', 'discount_pct']

        unit_price  discount_pct
count    12.000000     11.000000
mean   1082.333333     13.636364
std     318.614425     30.748245
min     799.000000      0.000000
25%     799.000000      0.000000
50%     999.000000      5.000000
75%    1499.000000     10.000000
max    1499.000000    105.000000

# Convert Date Columns

In [11]:
# Detect columns containing date or time in their names
date_columns = [
    column for column in orders.columns
    if "date" in column.lower() or "time" in column.lower()
]

# Display detected date columns
print("Detected Date Columns:", date_columns)

# Convert date columns into datetime format
for column in date_columns:
    orders[column] = pd.to_datetime(
        orders[column],
        errors="coerce"
    )

# Display updated data types
if date_columns:
    display(orders[date_columns].dtypes)
else:
    print("No date column found.")

Detected Date Columns: ['order_date']

order_date    datetime64[us]
dtype: object

# Display Complete Dataset

In [12]:
# Display the complete dataset
display(orders)

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,NaT,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-01-05,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
5,RT-1005,2026-01-09,Fresher,NaN,Mentor Session,1,999,0.0,Failed
6,RT-1006,NaT,Student,Pune,Learning Kit,-1,799,10.0,Paid
7,RT-1007,2026-01-12,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
8,RT-1008,2026-01-14,Fresher,Bengaluru,Course Access,two,1499,0.0,Pending
9,RT-1009,2026-01-16,Student,Chennai,Learning Kit,1,799,0.0,Paid
10,RT-1010,2026-01-18,Professional,Delhi,Course Access,2,1499,15.0,Refunded
11,RT-1011,NaT,Student,Kochi,Mentor Session,1,999,0.0,Paid

# Calculate Sales and Discount

In [13]:
# Convert quantity column into numeric values.
# Invalid values such as "two" will become NaN.
orders["quantity_numeric"] = pd.to_numeric(
    orders["quantity"],
    errors="coerce"
)

# Convert unit price column into numeric values.
orders["unit_price_numeric"] = pd.to_numeric(
    orders["unit_price"],
    errors="coerce"
)

# Convert discount percentage into numeric values.
orders["discount_numeric"] = pd.to_numeric(
    orders["discount_pct"],
    errors="coerce"
)

# Calculate gross sales before discount.
orders["gross_sales"] = (
    orders["quantity_numeric"] *
    orders["unit_price_numeric"]
)

# Calculate discount amount.
orders["discount_amount"] = (
    orders["gross_sales"] *
    orders["discount_numeric"] / 100
)

# Calculate net sales after discount.
orders["net_sales"] = (
    orders["gross_sales"] -
    orders["discount_amount"]
)

# Display calculated sales columns.
display(
    orders[
        [
            "order_id",
            "quantity_numeric",
            "unit_price_numeric",
            "discount_numeric",
            "gross_sales",
            "discount_amount",
            "net_sales"
        ]
    ]
)

,order_id,quantity_numeric,unit_price_numeric,discount_numeric,gross_sales,discount_amount,net_sales
0,RT-1001,2.0,799,10.0,1598.0,159.80,1438.20
1,RT-1002,1.0,1499,0.0,1499.0,0.00,1499.00
2,RT-1003,1.0,1499,NaN,1499.0,NaN,NaN
3,RT-1004,3.0,799,5.0,2397.0,119.85,2277.15
4,RT-1004,3.0,799,5.0,2397.0,119.85,2277.15
5,RT-1005,1.0,999,0.0,999.0,0.00,999.00
6,RT-1006,-1.0,799,10.0,-799.0,-79.90,-719.10
7,RT-1007,2.0,999,105.0,1998.0,2097.90,-99.90
8,RT-1008,NaN,1499,0.0,NaN,NaN,NaN
9,RT-1009,1.0,799,0.0,799.0,0.00,799.00
10,RT-1010,2.0,1499,15.0,2998.0,449.70,2548.30
11,RT-1011,1.0,999,0.0,999.0,0.00,999.00

# Calculate KPI Values

In [14]:
# Calculate total gross sales before discount.
total_gross_sales = orders["gross_sales"].sum()

# Calculate total discount amount.
total_discount = orders["discount_amount"].sum()

# Calculate total net sales after discount.
total_net_sales = orders["net_sales"].sum()

# Calculate total valid quantity sold.
total_quantity = orders["quantity_numeric"].sum()

# Calculate total unique orders.
total_orders = orders["order_id"].nunique()

# Calculate average order value.
average_order_value = total_net_sales / total_orders

# Display all KPI values.
print("Total Gross Sales:", total_gross_sales)
print("Total Discount:", total_discount)
print("Total Net Sales:", total_net_sales)
print("Total Quantity:", total_quantity)
print("Total Orders:", total_orders)
print("Average Order Value:", average_order_value)

Total Gross Sales: 16384.0
Total Discount: 2867.2
Total Net Sales: 12017.8
Total Quantity: 16.0
Total Orders: 11
Average Order Value: 1092.5272727272727

# Create KPI Dictionary

In [15]:
# Create a KPI dictionary according to available columns.
kpi_dictionary = pd.DataFrame({

    # Name of each KPI.
    "KPI Name": [
        "Total Gross Sales",
        "Total Discount",
        "Total Net Sales",
        "Total Quantity",
        "Total Orders",
        "Average Order Value"
    ],

    # Definition of each KPI.
    "Definition": [
        "Total sales before discount",
        "Total discount amount applied",
        "Total sales after discount",
        "Total valid quantity sold",
        "Total number of unique orders",
        "Average net sales per order"
    ],

    # Formula used to calculate each KPI.
    "Formula": [
        "SUM(quantity * unit_price)",
        "SUM(gross_sales * discount_pct / 100)",
        "SUM(gross_sales - discount_amount)",
        "SUM(valid quantity)",
        "COUNT DISTINCT(order_id)",
        "Total Net Sales / Total Orders"
    ],

    # Business meaning of each KPI.
    "Business Meaning": [
        "Measures total sales before discount",
        "Measures discount given to customers",
        "Measures actual sales after discount",
        "Measures total product quantity",
        "Measures order demand",
        "Measures average order value"
    ]
})

# Display the KPI dictionary.
display(kpi_dictionary)

,KPI Name,Definition,Formula,Business Meaning
0,Total Gross Sales,Total sales before discount,SUM(quantity * unit_price),Measures total sales before discount
1,Total Discount,Total discount amount applied,SUM(gross_sales * discount_pct / 100),Measures discount given to customers
2,Total Net Sales,Total sales after discount,SUM(gross_sales - discount_amount),Measures actual sales after discount
3,Total Quantity,Total valid quantity sold,SUM(valid quantity),Measures total product quantity
4,Total Orders,Total number of unique orders,COUNT DISTINCT(order_id),Measures order demand
5,Average Order Value,Average net sales per order,Total Net Sales / Total Orders,Measures average order value

# Create KPI Summary

In [16]:
# Create a summary table containing KPI values.
kpi_summary = pd.DataFrame({

    # KPI names.
    "KPI": [
        "Total Gross Sales",
        "Total Discount",
        "Total Net Sales",
        "Total Quantity",
        "Total Orders",
        "Average Order Value"
    ],

    # Calculated KPI values.
    "Value": [
        total_gross_sales,
        total_discount,
        total_net_sales,
        total_quantity,
        total_orders,
        average_order_value
    ]
})

# Display the KPI summary.
display(kpi_summary)

                   KPI         Value
0    Total Gross Sales  16384.000000
1       Total Discount   2867.200000
2      Total Net Sales  12017.800000
3       Total Quantity     16.000000
4         Total Orders     11.000000
5  Average Order Value   1092.527273

# Data Quality Report

In [17]:
# Count total missing values in the dataset.
total_missing_values = orders.isnull().sum().sum()

# Count total duplicate rows.
total_duplicate_rows = orders.duplicated().sum()

# Count negative quantity values.
negative_quantity_values = (
    orders["quantity_numeric"] < 0
).sum()

# Count invalid quantity values.
invalid_quantity_values = (
    orders["quantity_numeric"].isnull()
).sum()

# Count invalid discount values.
invalid_discount_values = (
    (orders["discount_numeric"] < 0) |
    (orders["discount_numeric"] > 100)
).sum()

# Create data quality report.
data_quality_report = pd.DataFrame({

    # Name of each quality check.
    "Check": [
        "Total Rows",
        "Total Columns",
        "Total Missing Values",
        "Duplicate Rows",
        "Negative Quantity Values",
        "Invalid Quantity Values",
        "Invalid Discount Values"
    ],

    # Result of each quality check.
    "Result": [
        orders.shape[0],
        orders.shape[1],
        total_missing_values,
        total_duplicate_rows,
        negative_quantity_values,
        invalid_quantity_values,
        invalid_discount_values
    ],

    # Status of each quality check.
    "Status": [
        "Pass",
        "Pass",
        "Pass" if total_missing_values == 0 else "Review Required",
        "Pass" if total_duplicate_rows == 0 else "Review Required",
        "Pass" if negative_quantity_values == 0 else "Review Required",
        "Pass" if invalid_quantity_values == 0 else "Review Required",
        "Pass" if invalid_discount_values == 0 else "Review Required"
    ]
})

# Display the data quality report.
display(data_quality_report)

                      Check  Result           Status
0                Total Rows      12             Pass
1             Total Columns      15             Pass
2      Total Missing Values      12  Review Required
3            Duplicate Rows       1  Review Required
4  Negative Quantity Values       1  Review Required
5   Invalid Quantity Values       1  Review Required
6   Invalid Discount Values       1  Review Required

# Missing Values Report

In [18]:
# Create a detailed missing values report.
missing_values_report = pd.DataFrame({

    # Column names.
    "Column": orders.columns,

    # Number of missing values in each column.
    "Missing Values": orders.isnull().sum().values,

    # Percentage of missing values in each column.
    "Missing Percentage": (
        orders.isnull().sum().values / len(orders)
    ) * 100
})

# Display the missing values report.
display(missing_values_report)

                Column  Missing Values  Missing Percentage
0             order_id               0            0.000000
1           order_date               3           25.000000
2     customer_segment               0            0.000000
3                 city               1            8.333333
4             category               0            0.000000
5             quantity               0            0.000000
6           unit_price               0            0.000000
7         discount_pct               1            8.333333
8       payment_status               0            0.000000
9     quantity_numeric               1            8.333333
10  unit_price_numeric               0            0.000000
11    discount_numeric               1            8.333333
12         gross_sales               1            8.333333
13     discount_amount               2           16.666667
14           net_sales               2           16.666667

# Duplicate Rows Report

In [19]:
# Select all duplicate rows.
duplicate_rows = orders[
    orders.duplicated(keep=False)
]

# Display duplicate rows.
display(duplicate_rows)

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status,quantity_numeric,unit_price_numeric,discount_numeric,gross_sales,discount_amount,net_sales
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid,3.0,799,5.0,2397.0,119.85,2277.15
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid,3.0,799,5.0,2397.0,119.85,2277.15

# Save Data Quality CSV

In [20]:
# Save the data quality report as a CSV file.
data_quality_report.to_csv(
    "data_quality_report.csv",
    index=False
)

# Print confirmation message.
print("data_quality_report.csv created successfully.")

data_quality_report.csv created successfully.

# Create Excel Workbook

In [21]:
# Create an Excel workbook with multiple sheets.
with pd.ExcelWriter(
    "KPI_Dictionary_and_Data_Quality.xlsx",
    engine="openpyxl"
) as writer:

    # Save KPI dictionary in Excel.
    kpi_dictionary.to_excel(
        writer,
        sheet_name="KPI Dictionary",
        index=False
    )

    # Save KPI summary in Excel.
    kpi_summary.to_excel(
        writer,
        sheet_name="KPI Summary",
        index=False
    )

    # Save data quality report in Excel.
    data_quality_report.to_excel(
        writer,
        sheet_name="Data Quality Report",
        index=False
    )

    # Save missing values report in Excel.
    missing_values_report.to_excel(
        writer,
        sheet_name="Missing Values",
        index=False
    )

    # Save duplicate rows in Excel.
    duplicate_rows.to_excel(
        writer,
        sheet_name="Duplicate Rows",
        index=False
    )

# Print confirmation message.
print("KPI_Dictionary_and_Data_Quality.xlsx created successfully.")

KPI_Dictionary_and_Data_Quality.xlsx created successfully.

# Check Final Files

In [22]:
# Display all files in the current notebook folder.
print("Files in Current Folder:")

for file in os.listdir():
    print(file)

Files in Current Folder:
.ipynb_checkpoints
data_quality_report.csv
KPI_Dictionary_and_Data_Quality.xlsx
Retail Sales KPI & Data Quality Analysis.ipynb
retail-data-dictionary.csv
retail-orders-raw.csv

# Final Project Output

In [23]:
# Display final KPI summary.
print("FINAL KPI SUMMARY")
display(kpi_summary)

# Display final data quality report.
print("FINAL DATA QUALITY REPORT")
display(data_quality_report)

# Print completion message.
print("Retail Sales KPI and Data Quality Analysis completed successfully.")

FINAL KPI SUMMARY

                   KPI         Value
0    Total Gross Sales  16384.000000
1       Total Discount   2867.200000
2      Total Net Sales  12017.800000
3       Total Quantity     16.000000
4         Total Orders     11.000000
5  Average Order Value   1092.527273

FINAL DATA QUALITY REPORT

                      Check  Result           Status
0                Total Rows      12             Pass
1             Total Columns      15             Pass
2      Total Missing Values      12  Review Required
3            Duplicate Rows       1  Review Required
4  Negative Quantity Values       1  Review Required
5   Invalid Quantity Values       1  Review Required
6   Invalid Discount Values       1  Review Required

Retail Sales KPI and Data Quality Analysis completed successfully.