# Import Libraries

In [1]:
# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

# Load Dataset

In [2]:
# Load raw CSV dataset
df = pd.read_csv("raw_dataset.csv")

# Store original dataset details
original_rows = df.shape[0]
original_columns = df.shape[1]
original_missing_values = df.isnull().sum().sum()
original_duplicates = df.duplicated().sum()

print("Dataset loaded successfully!")
print("Dataset Shape:", df.shape)

Dataset loaded successfully!
Dataset Shape: (34500, 17)

# Display First Five Rows

In [3]:
# Display first five rows
display(df.head())

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,West,No,139.47,7.88,31.17,60,Female
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,No,24.73,4.60,-2.62,37,Male
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,North,No,166.80,6.58,13.44,34,Male
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,South,No,63.67,5.50,2.14,21,Female
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,East,No,13.88,2.74,1.15,39,Male

# Display Dataset Information

In [4]:
# Display dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            34500 non-null  str
 1   customer_id         34500 non-null  str
 2   product_id          34500 non-null  str
 3   category            34500 non-null  str
 4   price               34500 non-null  float64
 5   discount            34500 non-null  float64
 6   quantity            34500 non-null  int64
 7   payment_method      34500 non-null  str
 8   order_date          34500 non-null  str
 9   delivery_time_days  34500 non-null  int64
 10  region              34500 non-null  str
 11  returned            34500 non-null  str
 12  total_amount        34500 non-null  float64
 13  shipping_cost       34500 non-null  float64
 14  profit_margin       34500 non-null  float64
 15  customer_age        34500 non-null  int64
 16  customer_gender     34500 non-null  str
dtypes: float64(5), int64(3), str(9)
memory usage: 4.5 MB

# Statistical Summary

In [5]:
# Display statistical summary
display(df.describe(include="all"))

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
count,34500,34500,34500,34500,34500.000000,34500.000000,34500.000000,34500,34500,34500.000000,34500,34500,34500.000000,34500.000000,34500.000000,34500.000000,34500
unique,34500,7903,24912,7,NaN,NaN,NaN,6,731,NaN,5,2,NaN,NaN,NaN,NaN,3
top,O100000,C11573,P200645,Fashion,NaN,NaN,NaN,Credit Card,2024-12-04,NaN,South,No,NaN,NaN,NaN,NaN,Female
freq,1,13,7,6254,NaN,NaN,NaN,12170,70,NaN,7584,32597,NaN,NaN,NaN,NaN,16818
mean,NaN,NaN,NaN,NaN,119.391632,0.049291,1.490725,NaN,NaN,4.814203,NaN,NaN,170.008494,6.152120,28.116505,43.474377,NaN
std,NaN,NaN,NaN,NaN,195.620477,0.069894,0.932270,NaN,NaN,1.242141,NaN,NaN,357.503014,2.389539,53.352947,14.980682,NaN
min,NaN,NaN,NaN,NaN,1.010000,0.000000,1.000000,NaN,NaN,3.000000,NaN,NaN,0.820000,0.000000,-6.200000,18.000000,NaN
25%,NaN,NaN,NaN,NaN,16.690000,0.000000,1.000000,NaN,NaN,4.000000,NaN,NaN,19.710000,4.420000,1.500000,31.000000,NaN
50%,NaN,NaN,NaN,NaN,45.660000,0.000000,1.000000,NaN,NaN,5.000000,NaN,NaN,56.820000,6.090000,10.550000,43.000000,NaN
75%,NaN,NaN,NaN,NaN,130.950000,0.100000,2.000000,NaN,NaN,6.000000,NaN,NaN,168.530000,7.830000,33.132500,56.000000,NaN
max,NaN,NaN,NaN,NaN,2930.470000,0.300000,5.000000,NaN,NaN,13.000000,NaN,NaN,12931.800000,15.650000,1536.170000,69.000000,NaN

# Check Missing Values

In [6]:
# Check missing values in each column
missing_values = df.isnull().sum()

# Calculate missing percentage
missing_percentage = (df.isnull().sum() / len(df)) * 100

# Create missing value summary
missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percentage
})

display(missing_summary)

                    Missing Values  Missing Percentage
order_id                         0                 0.0
customer_id                      0                 0.0
product_id                       0                 0.0
category                         0                 0.0
price                            0                 0.0
discount                         0                 0.0
quantity                         0                 0.0
payment_method                   0                 0.0
order_date                       0                 0.0
delivery_time_days               0                 0.0
region                           0                 0.0
returned                         0                 0.0
total_amount                     0                 0.0
shipping_cost                    0                 0.0
profit_margin                    0                 0.0
customer_age                     0                 0.0
customer_gender                  0                 0.0

# Check Duplicate Records

In [7]:
# Count duplicate records
duplicate_count = df.duplicated().sum()

print("Duplicate Records:", duplicate_count)

Duplicate Records: 0

# Standardize Column Names

In [8]:
# Convert column names into lowercase
df.columns = df.columns.str.lower()

# Replace spaces with underscores
df.columns = df.columns.str.replace(" ", "_")

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

print("Standardized Column Names:")
print(df.columns.tolist())

Standardized Column Names:
['order_id', 'customer_id', 'product_id', 'category', 'price', 'discount', 'quantity', 'payment_method', 'order_date', 'delivery_time_days', 'region', 'returned', 'total_amount', 'shipping_cost', 'profit_margin', 'customer_age', 'customer_gender']

# Remove Extra Spaces

In [9]:
# Select text columns
text_columns = df.select_dtypes(include="object").columns

# Remove extra spaces from text columns
for column in text_columns:
    df[column] = df[column].str.strip()

print("Extra spaces removed successfully!")

Extra spaces removed successfully!

C:\Users\prern\AppData\Local\Temp\ipykernel_19556\3412310099.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

# Correct Data Types

In [10]:
# Convert object columns to numeric wherever possible
for column in df.columns:
    if df[column].dtype == "object":
        converted_column = pd.to_numeric(
            df[column],
            errors="ignore"
        )
        df[column] = converted_column

print("Data types corrected successfully!")
display(df.dtypes)

Data types corrected successfully!

order_id                  str
customer_id               str
product_id                str
category                  str
price                 float64
discount              float64
quantity                int64
payment_method            str
order_date                str
delivery_time_days      int64
region                    str
returned                  str
total_amount          float64
shipping_cost         float64
profit_margin         float64
customer_age            int64
customer_gender           str
dtype: object

# Handle Missing Values

In [11]:
# Handle missing values in numerical columns using median
numeric_columns = df.select_dtypes(include=np.number).columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())

# Handle missing values in text columns using mode
categorical_columns = df.select_dtypes(include="object").columns

for column in categorical_columns:
    if df[column].isnull().sum() > 0:
        df[column] = df[column].fillna(
            df[column].mode()[0]
        )

print("Missing values handled successfully!")

Missing values handled successfully!

C:\Users\prern\AppData\Local\Temp\ipykernel_19556\27641721.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include="object").columns

# Convert Date Columns

In [12]:
# Detect possible date columns
date_columns = [
    column for column in df.columns
    if "date" in column or "time" in column
]

# Convert date columns into datetime format
for column in date_columns:
    df[column] = pd.to_datetime(
        df[column],
        errors="coerce"
    )

print("Date columns converted successfully!")
print(date_columns)

Date columns converted successfully!
['order_date', 'delivery_time_days']

# Remove Duplicate Records

In [14]:
# Check duplicate records
duplicate_count = df.duplicated().sum()

print("Duplicate Records:", duplicate_count)

# Remove duplicates only if duplicates are present
if duplicate_count > 0:
    df = df.drop_duplicates()
    df = df.reset_index(drop=True)
    print("Duplicate records removed!")
else:
    print("No duplicate records found. No changes required.")

Duplicate Records: 0
No duplicate records found. No changes required.

# Detect Outliers

In [15]:
# Detect outliers using the IQR method
numeric_columns = df.select_dtypes(include=np.number).columns

outlier_summary = {}

for column in numeric_columns:

    # Calculate Q1 and Q3
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    # Calculate IQR
    IQR = Q3 - Q1

    # Calculate limits
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    # Count outliers
    outlier_count = (
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    ).sum()

    outlier_summary[column] = outlier_count

# Display outlier summary
outlier_df = pd.DataFrame(
    list(outlier_summary.items()),
    columns=["Column", "Outlier Count"]
)

display(outlier_df)

          Column  Outlier Count
0          price           3632
1       discount            704
2       quantity           2070
3   total_amount           3792
4  shipping_cost             48
5  profit_margin           3025
6   customer_age              0

# Handle Outliers

In [16]:
# Handle outliers using IQR clipping
for column in numeric_columns:

    # Calculate Q1 and Q3
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    # Calculate IQR
    IQR = Q3 - Q1

    # Calculate limits
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    # Clip extreme values
    df[column] = df[column].clip(
        lower=lower_limit,
        upper=upper_limit
    )

print("Outliers handled successfully!")

Outliers handled successfully!

# Feature Engineering - Year and Month

In [17]:
# Create year and month features from date columns
for column in date_columns:

    # Create year column
    df[column + "_year"] = df[column].dt.year

    # Create month column
    df[column + "_month"] = df[column].dt.month

print("Year and month features created!")
display(df.head())

Year and month features created!

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender,order_date_year,order_date_month,delivery_time_days_year,delivery_time_days_month
0,O100000,C17270,P234890,Home,164.08,0.15,1.0,Credit Card,2023-12-23,1970-01-01 00:00:00.000000004,West,No,139.47,7.88,31.17,60,Female,2023,12,1970,1
1,O100001,C17603,P228204,Grocery,24.73,0.00,1.0,Credit Card,2025-04-03,1970-01-01 00:00:00.000000006,South,No,24.73,4.60,-2.62,37,Male,2025,4,1970,1
2,O100002,C10860,P213892,Electronics,175.58,0.05,1.0,Credit Card,2024-10-08,1970-01-01 00:00:00.000000004,North,No,166.80,6.58,13.44,34,Male,2024,10,1970,1
3,O100003,C15390,P208689,Electronics,63.67,0.00,1.0,UPI,2024-09-14,1970-01-01 00:00:00.000000006,South,No,63.67,5.50,2.14,21,Female,2024,9,1970,1
4,O100004,C15226,P228063,Home,16.33,0.15,1.0,COD,2024-12-21,1970-01-01 00:00:00.000000006,East,No,13.88,2.74,1.15,39,Male,2024,12,1970,1

# Calculate Sales and Profit Features

In [18]:
# Check whether required columns are available
if all(column in df.columns for column in ["price", "quantity"]):

    # Calculate total sales
    df["calculated_sales"] = (
        df["price"] * df["quantity"]
    )

    print("Sales column created!")

# Calculate estimated profit if shipping cost is available
if all(
    column in df.columns
    for column in ["calculated_sales", "shipping_cost"]
):

    # Calculate estimated profit
    df["estimated_profit"] = (
        df["calculated_sales"] -
        df["shipping_cost"]
    )

    print("Estimated profit column created!")

Sales column created!
Estimated profit column created!

# Before and After Comparison

In [19]:
# Create before and after cleaning comparison
comparison = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Missing Values",
        "Duplicate Records"
    ],

    "Before Cleaning": [
        original_rows,
        original_columns,
        original_missing_values,
        original_duplicates
    ],

    "After Cleaning": [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

display(comparison)

              Metric  Before Cleaning  After Cleaning
0         Total Rows            34500           34500
1      Total Columns               17              23
2     Missing Values                0               0
3  Duplicate Records                0               0

# Final Dataset Check

In [20]:
# Display final dataset shape
print("Final Dataset Shape:", df.shape)

# Check missing values
print("\nMissing Values After Cleaning:")
display(df.isnull().sum())

# Check duplicate records
print(
    "\nDuplicate Records After Cleaning:",
    df.duplicated().sum()
)

# Display cleaned dataset
display(df.head(10))

Final Dataset Shape: (34500, 23)

Missing Values After Cleaning:

order_id                    0
customer_id                 0
product_id                  0
category                    0
price                       0
discount                    0
quantity                    0
payment_method              0
order_date                  0
delivery_time_days          0
region                      0
returned                    0
total_amount                0
shipping_cost               0
profit_margin               0
customer_age                0
customer_gender             0
order_date_year             0
order_date_month            0
delivery_time_days_year     0
delivery_time_days_month    0
calculated_sales            0
estimated_profit            0
dtype: int64

Duplicate Records After Cleaning: 0

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender,order_date_year,order_date_month,delivery_time_days_year,delivery_time_days_month,calculated_sales,estimated_profit
0,O100000,C17270,P234890,Home,164.08,0.15,1.0,Credit Card,2023-12-23,1970-01-01 00:00:00.000000004,West,No,139.47,7.88,31.17,60,Female,2023,12,1970,1,164.08,156.20
1,O100001,C17603,P228204,Grocery,24.73,0.00,1.0,Credit Card,2025-04-03,1970-01-01 00:00:00.000000006,South,No,24.73,4.60,-2.62,37,Male,2025,4,1970,1,24.73,20.13
2,O100002,C10860,P213892,Electronics,175.58,0.05,1.0,Credit Card,2024-10-08,1970-01-01 00:00:00.000000004,North,No,166.80,6.58,13.44,34,Male,2024,10,1970,1,175.58,169.00
3,O100003,C15390,P208689,Electronics,63.67,0.00,1.0,UPI,2024-09-14,1970-01-01 00:00:00.000000006,South,No,63.67,5.50,2.14,21,Female,2024,9,1970,1,63.67,58.17
4,O100004,C15226,P228063,Home,16.33,0.15,1.0,COD,2024-12-21,1970-01-01 00:00:00.000000006,East,No,13.88,2.74,1.15,39,Male,2024,12,1970,1,16.33,13.59
5,O100005,C15191,P214062,Beauty,53.91,0.10,2.0,Credit Card,2024-04-14,1970-01-01 00:00:00.000000005,South,No,97.04,6.32,37.35,35,Female,2024,4,1970,1,107.82,101.50
6,O100006,C13772,P201363,Electronics,266.50,0.00,1.0,PayPal,2025-05-20,1970-01-01 00:00:00.000000005,East,No,266.50,9.10,22.88,49,Male,2025,5,1970,1,266.50,257.40
7,O100007,C13092,P216691,Beauty,9.98,0.00,1.0,Credit Card,2023-09-14,1970-01-01 00:00:00.000000004,West,No,9.98,4.51,-0.02,66,Other,2023,9,1970,1,9.98,5.47
8,O100008,C15734,P202751,Fashion,6.61,0.05,1.0,Debit Card,2023-10-23,1970-01-01 00:00:00.000000006,West,No,6.28,3.43,-1.23,37,Female,2023,10,1970,1,6.61,3.18
9,O100009,C16265,P207782,Grocery,10.91,0.00,1.0,Credit Card,2023-10-31,1970-01-01 00:00:00.000000006,South,No,10.91,2.76,-1.89,56,Male,2023,10,1970,1,10.91,8.15

# Export Clean Dataset

In [22]:
# Export cleaned dataset as clean_dataset.csv
df.to_csv(
    "clean_dataset.csv",
    index=False
)

print("clean_dataset.csv created successfully!")

clean_dataset.csv created successfully!

# Verify Exported File

In [23]:
# Load the exported cleaned CSV file
clean_dataset = pd.read_csv("clean_dataset.csv")

# Display exported file details
print("Exported Dataset Shape:", clean_dataset.shape)

# Display first five rows
display(clean_dataset.head())

Exported Dataset Shape: (34500, 23)

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender,order_date_year,order_date_month,delivery_time_days_year,delivery_time_days_month,calculated_sales,estimated_profit
0,O100000,C17270,P234890,Home,164.08,0.15,1.0,Credit Card,2023-12-23,1970-01-01 00:00:00.000000004,West,No,139.47,7.88,31.17,60,Female,2023,12,1970,1,164.08,156.20
1,O100001,C17603,P228204,Grocery,24.73,0.00,1.0,Credit Card,2025-04-03,1970-01-01 00:00:00.000000006,South,No,24.73,4.60,-2.62,37,Male,2025,4,1970,1,24.73,20.13
2,O100002,C10860,P213892,Electronics,175.58,0.05,1.0,Credit Card,2024-10-08,1970-01-01 00:00:00.000000004,North,No,166.80,6.58,13.44,34,Male,2024,10,1970,1,175.58,169.00
3,O100003,C15390,P208689,Electronics,63.67,0.00,1.0,UPI,2024-09-14,1970-01-01 00:00:00.000000006,South,No,63.67,5.50,2.14,21,Female,2024,9,1970,1,63.67,58.17
4,O100004,C15226,P228063,Home,16.33,0.15,1.0,COD,2024-12-21,1970-01-01 00:00:00.000000006,East,No,13.88,2.74,1.15,39,Male,2024,12,1970,1,16.33,13.59

# Final Conclusion

In [24]:
# Display final project conclusion
print("==============================================")
print("TASK 3 COMPLETED SUCCESSFULLY")
print("==============================================")
print("Dataset loaded using Pandas.")
print("Missing values handled.")
print("Duplicate records removed.")
print("Data types corrected.")
print("Outliers detected and handled.")
print("Year and month features created.")
print("Sales and profit features calculated.")
print("clean_dataset.csv exported successfully.")
print("==============================================")

==============================================
TASK 3 COMPLETED SUCCESSFULLY
==============================================
Dataset loaded using Pandas.
Missing values handled.
Duplicate records removed.
Data types corrected.
Outliers detected and handled.
Year and month features created.
Sales and profit features calculated.
clean_dataset.csv exported successfully.
==============================================